# Generated by Django 3.2 on 2022-05-22 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20220521_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 22)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 25)),
        ),
    ]
