# Generated by Django 3.2 on 2022-05-25 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20220524_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 35, 12, 839716)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 14, 35, 12, 837486)),
        ),
    ]
