# Generated by Django 3.2 on 2022-05-25 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_order_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 22, 36, 26, 619802, tzinfo=utc)),
        ),
    ]
