# Generated by Django 3.2 on 2022-06-03 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_alter_order_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 16, 26, 20, 732813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 16, 26, 20, 732813, tzinfo=utc)),
        ),
    ]
