# Generated by Django 3.2 on 2022-06-04 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20220603_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 0, 38, 43, 410124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 0, 38, 43, 410124, tzinfo=utc)),
        ),
    ]
