# Generated by Django 3.2 on 2022-06-11 15:21

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20220611_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='gear_or_equipments',
            new_name='equipments_provided',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='number_of_people',
            new_name='number_of_poeple',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='time_taken_for_activities',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='will_you_provide_gear_or_equipments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='starting_point',
        ),
        migrations.AddField(
            model_name='activities',
            name='children_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='covid_19_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='covid_19_compliance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='damage_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='duration_of_activity',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='equipments_required_by_user_to_bring',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="What gear or equipment is needed and won't be provided by you? Separate each gear or equipments by using ' , '", null=True, size=None),
        ),
        migrations.AddField(
            model_name='activities',
            name='group_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='group_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='max_number_of_people',
            field=models.PositiveIntegerField(default=1, help_text='Enter this field if the pricing plan is per people'),
        ),
        migrations.AddField(
            model_name='activities',
            name='max_number_of_sessions',
            field=models.PositiveIntegerField(default=1, help_text='Enter this field if the pricing plan is per session'),
        ),
        migrations.AddField(
            model_name='activities',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='price_per_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='price_per_person',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='price_per_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='refaundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='refund_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='session_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='session_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='non_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_groups',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='pricing_type',
            field=models.CharField(choices=[('PER PERSON', 'PER PERSON'), ('PER GROUP', 'PER GROUP'), ('PER SESSION', 'PER SESSION')], default='PER PERSON', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='non_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_groups',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_poeple',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_type',
            field=models.CharField(choices=[('PER PERSON', 'PER PERSON'), ('PER GROUP', 'PER GROUP'), ('PER SESSION', 'PER SESSION')], default='PER PERSON', max_length=50),
        ),
        migrations.AlterField(
            model_name='activities',
            name='max_number_of_groups',
            field=models.PositiveIntegerField(default=1, help_text='Enter this field if the pricing plan is per group'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 17, 24, 530847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 17, 24, 530847, tzinfo=utc)),
        ),
    ]
