# Generated by Django 3.2 on 2022-06-11 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0037_auto_20220611_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='max_number_of_people_in_a_group',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='activities',
            name='max_number_of_groups',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activities',
            name='max_number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activities',
            name='max_number_of_sessions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 58, 38, 780028, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 58, 38, 780028, tzinfo=utc)),
        ),
    ]
