# Generated by Django 3.2 on 2022-06-12 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_auto_20220611_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='number_of_poeple',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number_of_poeple',
            new_name='number_of_people',
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 1, 23, 9, 77664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 1, 23, 9, 77664, tzinfo=utc)),
        ),
    ]
