# Generated by Django 3.2 on 2022-06-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0053_auto_20220616_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_date',
        ),
    ]
