# Generated by Django 3.2 on 2022-06-30 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0056_remove_activities_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='equipments_provided',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='equipments_required_by_user_to_bring',
        ),
        migrations.AddField(
            model_name='activities',
            name='min_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EnquipmentRequiredByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquipment_required_by_user', to='activities.activities')),
            ],
        ),
        migrations.CreateModel(
            name='EnquipmentProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquipment_provided', to='activities.activities')),
            ],
        ),
    ]
