# Generated by Django 3.2 on 2022-06-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0057_auto_20220630_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='pricing_type',
            field=models.CharField(choices=[('REASONABLE', 'REASONABLE'), ('MID-RANGE', 'MID-RANGE'), ('HIGH-END', 'HIGH-END')], default='REASONABLE', max_length=100),
        ),
    ]
