# Generated by Django 3.2 on 2022-06-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0059_auto_20220630_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='max_number_of_people',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='max_number_of_sessions',
        ),
    ]
