# Generated by Django 3.2 on 2022-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0060_auto_20220630_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number_of_groups_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_people_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_sessions_non_resident',
            field=models.IntegerField(default=0),
        ),
    ]
