# Generated by Django 3.2 on 2022-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0061_auto_20220701_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='non_resident',
        ),
        migrations.RemoveField(
            model_name='order',
            name='non_resident',
        ),
        migrations.AlterField(
            model_name='cart',
            name='number_of_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number_of_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
