# Generated by Django 3.2 on 2022-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0063_facts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
