# Generated by Django 3.2 on 2022-07-31 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0064_alter_activities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Separate each tag by using ' , '", null=True, size=None),
        ),
    ]
