# Generated by Django 3.2 on 2022-08-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0065_activities_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitiesimage',
            options={'verbose_name': 'Experience Image', 'verbose_name_plural': 'Experience Images'},
        ),
        migrations.AlterModelOptions(
            name='enquipmentprovided',
            options={'verbose_name': 'Inclusions', 'verbose_name_plural': 'Inclusions'},
        ),
        migrations.AlterModelOptions(
            name='enquipmentrequiredbyuser',
            options={'verbose_name': 'What to bring', 'verbose_name_plural': 'What to bring'},
        ),
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name': 'Quick Fact', 'verbose_name_plural': 'Quick Facts'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='city',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='county'),
        ),
    ]
