# Generated by Django 3.2 on 2022-08-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0067_auto_20220823_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_groups_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_people_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_sessions_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
