# Generated by Django 3.2 on 2022-08-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0068_auto_20220824_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activities',
            name='price_non_resident',
            field=models.FloatField(default=0),
        ),
    ]
