# Generated by Django 3.2 on 2022-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0069_auto_20220824_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='price_is_flexible',
            field=models.BooleanField(default=False, help_text="This means they will be a 'from' price next to the price in the frontend. Eg from $100 per person"),
        ),
    ]
