# Generated by Django 3.2 on 2022-09-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0070_activities_price_is_flexible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
