# Generated by Django 3.2 on 2022-10-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Health', 'Health'), ('Relationship', 'Relationship'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Education', 'Education'), ('Science', 'Science'), ('Environment', 'Environment'), ('History', 'History'), ('Culture', 'Culture'), ('Winda research', 'Winda research'), ('Art', 'Art'), ('Music', 'Music'), ('Movies', 'Movies'), ('Games', 'Games'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='estimated_minute_read',
            field=models.IntegerField(default=5, help_text='Estimated time to read in minutes'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
