from .views import *
from django.urls import path


urlpatterns = [
    path("curated-trips/", CuratedTripListView.as_view(), name="curated-trips"),
    path(
        "curated-trips/<slug:slug>/",
        CuratedTripDetailView.as_view(),
        name="curated-trips-detail",
    ),
    path(
        "user-trips/",
        UserTripsListView.as_view(),
        name="user-trips",
    ),
    path(
        "user-trips/<slug:slug>/",
        UserTripsDetailView.as_view(),
        name="user-trips",
    ),
    path(
        "create-user-trip/",
        UserTripCreateView.as_view(),
        name="create-user-trip",
    ),
    path(
        "create-user-trip/<slug:trip_slug>/",
        UserTripCreateView.as_view(),
        name="create-user-trip",
    ),
    path(
        "user-trip/",
        UserTripListView.as_view(),
        name="user-trips",
    ),
    path(
        "user-trip/<slug>/",
        UserTripDetailView.as_view(),
        name="user-trips",
    ),
    path(
        "user-trip/stay/<slug>/",
        UserStayTripDetailView.as_view(),
        name="user-stay-trip",
    ),
    path(
        "user-trip/<trip_slug>/stay/create/",
        UserStayTripCreateView.as_view(),
        name="user-stay-trip-create",
    ),
    path(
        "user-trip/activity/<slug>/",
        UserActivityTripDetailView.as_view(),
        name="user-activity-trip",
    ),
    path(
        "user-trip/<trip_slug>/activity/create/",
        UserActivityTripCreateView.as_view(),
        name="user-activity-trip-create",
    ),
    path(
        "user-trip/transportation/<slug>/",
        UserTransportationTripDetailView.as_view(),
        name="user-transportation-trip",
    ),
    path(
        "user-trip/<trip_slug>/transportation/create/",
        UserTransportationTripCreateView.as_view(),
        name="user-transportation-trip-create",
    ),
]
