# Generated by Django 3.2 on 2022-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.IntegerField(blank=True, help_text='Select the day of this itinerary', null=True),
        ),
    ]
