# Generated by Django 3.2 on 2022-08-15 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0128_auto_20220812_2233'),
        ('activities', '0066_auto_20220809_0852'),
        ('transport', '0018_alter_transportation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curated_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(default='Untitled Trip', max_length=250)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTransportTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('starting_point', models.CharField(blank=True, max_length=250, null=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('user_need_a_driver', models.BooleanField(default=False)),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport_trip', to='curated_trip.usertrip')),
            ],
        ),
        migrations.CreateModel(
            name='UserStayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPPLE ROOM', 'TRIPPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM'), ('EXECUTIVE SUITE ROOM', 'EXECUTIVE SUITE ROOM'), ('FAMILY ROOM', 'FAMILY ROOM'), ('PRESIDENTIAL SUITE ROOM', 'PRESIDENTIAL SUITE ROOM'), ('EMPEROR SUITE ROOM', 'EMPEROR SUITE ROOM')], default='STANDARD', max_length=100)),
                ('num_of_adults', models.IntegerField(default=1)),
                ('num_of_children', models.IntegerField(default=0)),
                ('num_of_adults_non_resident', models.IntegerField(default=0)),
                ('num_of_children_non_resident', models.IntegerField(default=0)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodging.stays')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stay_trip', to='curated_trip.usertrip')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pricing_type', models.CharField(choices=[('REASONABLE', 'REASONABLE'), ('MID-RANGE', 'MID-RANGE'), ('HIGH-END', 'HIGH-END')], default='PER PERSON', max_length=50)),
                ('number_of_people', models.IntegerField(default=0)),
                ('number_of_people_non_resident', models.IntegerField(default=0)),
                ('number_of_sessions', models.IntegerField(default=0)),
                ('number_of_sessions_non_resident', models.IntegerField(default=0)),
                ('number_of_groups', models.IntegerField(default=0)),
                ('number_of_groups_non_resident', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activities')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_trip', to='curated_trip.usertrip')),
            ],
        ),
    ]
