# Generated by Django 3.2 on 2022-08-16 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curated_trip', '0002_useractivitytrip_userstaytrip_usertransporttrip_usertrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='paid',
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(default='Untitled Trip', max_length=250)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usertrip',
            name='trips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='curated_trip.usertrips'),
        ),
    ]
