# Generated by Django 3.2 on 2022-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0002_alter_itinerary_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='similartrips',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
