# Generated by Django 3.2 on 2022-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0003_similartrips_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similartrips',
            name='name',
        ),
        migrations.RemoveField(
            model_name='similartrips',
            name='curated_trip',
        ),
        migrations.AddField(
            model_name='similartrips',
            name='curated_trip',
            field=models.ManyToManyField(to='curated_trip.CuratedTrip'),
        ),
    ]
