# Generated by Django 3.2 on 2022-10-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0004_auto_20221022_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similartrips',
            name='curated_trip',
            field=models.ManyToManyField(related_name='similar_trips', to='curated_trip.CuratedTrip'),
        ),
    ]
