# Generated by Django 3.2 on 2022-08-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0004_auto_20220816_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='trips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='curated_trip.usertrips', verbose_name='Group Trip'),
        ),
    ]
