# Generated by Django 3.2 on 2022-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0005_alter_usertrip_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='starting_point',
        ),
        migrations.AddField(
            model_name='usertrips',
            name='starting_point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
