# Generated by Django 3.2 on 2022-10-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0006_auto_20221022_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryaccommodation',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_accommodations', to='curated_trip.itinerary'),
        ),
    ]
