# Generated by Django 3.2 on 2022-08-22 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0007_curatedtrip_essential_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedtrip',
            name='stop_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
