# Generated by Django 3.2 on 2022-11-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0009_requestinfooncustomtrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestinfooncustomtrip',
            options={'verbose_name': 'Request Info On Curated Trip', 'verbose_name_plural': 'Request Info On Curated Trips'},
        ),
        migrations.CreateModel(
            name='PricePlanC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_non_resident', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_plan_c', to='curated_trip.curatedtrip')),
            ],
            options={
                'verbose_name': 'Price Plan C',
                'verbose_name_plural': 'Price Plan C',
            },
        ),
        migrations.CreateModel(
            name='PricePlanB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_non_resident', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_plan_b', to='curated_trip.curatedtrip')),
            ],
            options={
                'verbose_name': 'Price Plan B',
                'verbose_name_plural': 'Price Plan B',
            },
        ),
        migrations.CreateModel(
            name='PricePlanA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_non_resident', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_plan_a', to='curated_trip.curatedtrip')),
            ],
            options={
                'verbose_name': 'Price Plan A',
                'verbose_name_plural': 'Price Plan A',
            },
        ),
    ]
