# Generated by Django 3.2 on 2022-11-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0010_auto_20221106_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplana',
            name='curated_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_a_price', to='curated_trip.curatedtrip'),
        ),
        migrations.AlterField(
            model_name='priceplanb',
            name='curated_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_b_price', to='curated_trip.curatedtrip'),
        ),
        migrations.AlterField(
            model_name='priceplanc',
            name='curated_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_c_price', to='curated_trip.curatedtrip'),
        ),
    ]
