# Generated by Django 3.2 on 2022-11-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0011_auto_20221106_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceplana',
            name='curated_trip',
        ),
        migrations.RemoveField(
            model_name='priceplanb',
            name='curated_trip',
        ),
        migrations.RemoveField(
            model_name='priceplanc',
            name='curated_trip',
        ),
        migrations.CreateModel(
            name='DateAndPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('is_not_available', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_and_pricing', to='curated_trip.curatedtrip')),
            ],
        ),
        migrations.AddField(
            model_name='priceplana',
            name='date_and_pricing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_a_price', to='curated_trip.dateandpricing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplanb',
            name='date_and_pricing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plan_b_price', to='curated_trip.dateandpricing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplanc',
            name='date_and_pricing',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='plan_c_price', to='curated_trip.dateandpricing'),
            preserve_default=False,
        ),
    ]
