# Generated by Django 3.2 on 2022-11-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0012_auto_20221106_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateandpricing',
            name='ending_date',
        ),
        migrations.AlterField(
            model_name='dateandpricing',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
