# Generated by Django 3.2 on 2022-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0013_auto_20221106_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateandpricing',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
