# Generated by Django 3.2 on 2022-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0014_dateandpricing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateandpricing',
            name='slug',
        ),
    ]
