# Generated by Django 3.2 on 2022-11-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0016_dateandpricing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceplana',
            name='date_and_pricing',
        ),
        migrations.RemoveField(
            model_name='priceplanb',
            name='date_and_pricing',
        ),
        migrations.RemoveField(
            model_name='priceplanc',
            name='date_and_pricing',
        ),
        migrations.AddField(
            model_name='priceplana',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_a_price', to='curated_trip.curatedtrip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplanb',
            name='trip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='plan_b_price', to='curated_trip.curatedtrip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplanc',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plan_c_price', to='curated_trip.curatedtrip'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DateAndPricing',
        ),
    ]
