# Generated by Django 3.2 on 2022-11-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0021_auto_20221107_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplana',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_a_price', to='curated_trip.curatedtrip'),
        ),
        migrations.AlterField(
            model_name='priceplanb',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_b_price', to='curated_trip.curatedtrip'),
        ),
        migrations.AlterField(
            model_name='priceplanc',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_c_price', to='curated_trip.curatedtrip'),
        ),
    ]
