# Generated by Django 3.2 on 2022-11-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0023_auto_20221107_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedtrip',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='curatedtrip',
            name='price',
        ),
        migrations.RemoveField(
            model_name='curatedtrip',
            name='price_non_resident',
        ),
    ]
