# Generated by Django 3.2 on 2022-11-08 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0024_auto_20221107_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('starting_date', models.DateField(default=django.utils.timezone.now)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('booking_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curated_trip.curatedtrip')),
            ],
            options={
                'verbose_name': 'Booked Trip',
                'verbose_name_plural': 'Booked Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
