# Generated by Django 3.2 on 2022-11-15 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0027_tripwizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripwizard',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
