# Generated by Django 3.2 on 2022-11-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0028_tripwizard_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripwizard',
            name='location',
        ),
    ]
