# Generated by Django 3.2 on 2023-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0033_remove_itinerary_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedtrip',
            name='valentine_offer',
            field=models.BooleanField(default=False),
        ),
    ]
