# Generated by Django 3.2 on 2023-01-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0034_curatedtrip_valentine_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplana',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceplanb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceplanc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
