# Generated by Django 3.2 on 2023-02-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_trip', '0035_auto_20230123_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ebook Email',
                'verbose_name_plural': 'Ebook Emails',
            },
        ),
    ]
