# Generated by Django 3.2 on 2022-05-26 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimage',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.AddField(
            model_name='grouptrip',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouptrip',
            name='starting_point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 20, 17, 12, 469704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grouptrip',
            name='trip',
            field=models.ManyToManyField(to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='grouptrip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupTripImage',
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
