# Generated by Django 3.2 on 2022-05-27 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20220526_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 15, 38, 168095, tzinfo=utc)),
        ),
    ]
