# Generated by Django 3.2 on 2022-05-27 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20220524_1820'),
        ('trip', '0003_alter_trip_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptrip',
            name='transport_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportation'),
        ),
        migrations.AlterField(
            model_name='grouptrip',
            name='trip',
            field=models.ManyToManyField(blank=True, null=True, to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 19, 46, 31, 584909, tzinfo=utc)),
        ),
    ]
