# Generated by Django 3.2 on 2022-05-27 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20220527_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptrip',
            name='trip',
            field=models.ManyToManyField(blank=True, to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 19, 47, 4, 175116, tzinfo=utc)),
        ),
    ]
