# Generated by Django 3.2 on 2022-05-27 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20220524_1820'),
        ('activities', '0017_alter_order_to_date'),
        ('lodging', '0059_alter_order_to_date'),
        ('trip', '0005_auto_20220527_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activities'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodging.stays'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 19, 56, 16, 273002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportation'),
        ),
    ]
