# Generated by Django 3.2 on 2022-05-28 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20220527_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 1, 53, 34, 630870, tzinfo=utc)),
        ),
    ]
