# Generated by Django 3.2 on 2022-05-28 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_trip_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='nights',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 13, 50, 47, 123398, tzinfo=utc)),
        ),
    ]
