# Generated by Django 3.2 on 2022-06-02 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20220528_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 11, 1, 36, 467180, tzinfo=utc)),
        ),
    ]
