# Generated by Django 3.2 on 2022-06-03 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20220602_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 16, 26, 20, 739937, tzinfo=utc)),
        ),
    ]
