# Generated by Django 3.2 on 2022-06-05 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_alter_trip_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_transport_per_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='user_need_a_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 18, 2, 10, 862088, tzinfo=utc)),
        ),
    ]
