# Generated by Django 3.2 on 2022-06-06 01:10

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_auto_20220605_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 1, 10, 52, 598463, tzinfo=utc)),
        ),
    ]
