# Generated by Django 3.2 on 2022-06-09 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_alter_trip_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 8, 5, 56, 447012, tzinfo=utc)),
        ),
    ]
