# Generated by Django 3.2 on 2022-06-10 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_auto_20220610_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 4, 11, 3, 230400, tzinfo=utc)),
        ),
    ]
