# Generated by Django 3.2 on 2022-06-11 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_alter_trip_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity_non_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_groups',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_poeple',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_pricing_type',
            field=models.CharField(choices=[('PER PERSON', 'PER PERSON'), ('PER GROUP', 'PER GROUP'), ('PER SESSION', 'PER SESSION')], default='PER PERSON', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 17, 24, 591347, tzinfo=utc)),
        ),
    ]
