# Generated by Django 3.2 on 2022-06-11 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_auto_20220611_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 15, 58, 38, 789517, tzinfo=utc)),
        ),
    ]
