# Generated by Django 3.2 on 2022-06-12 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0029_auto_20220612_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 56, 53, 101595, tzinfo=utc)),
        ),
    ]
