# Generated by Django 3.2 on 2022-06-15 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0038_alter_trip_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptrip',
            name='is_public',
        ),
        migrations.AddField(
            model_name='grouptrip',
            name='name',
            field=models.CharField(default='Untitled Trip', max_length=250),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 11, 39, 9, 469153, tzinfo=utc)),
        ),
    ]
