# Generated by Django 3.2 on 2022-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0039_auto_20220615_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='number_of_days',
            new_name='transport_number_of_days',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='number_of_people',
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity_from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity_number_of_groups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity_number_of_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='stay_num_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
