# Generated by Django 3.2 on 2022-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0040_auto_20220615_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='checked_for_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='stay_is_not_available',
            field=models.BooleanField(default=False),
        ),
    ]
