# Generated by Django 3.2 on 2022-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0041_auto_20220621_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stay_plan',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPPLE ROOM', 'TRIPPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM'), ('FAMILY ROOM', 'FAMILY ROOM'), ('PRESIDENTIAL SUITE', 'PRESIDENTIAL SUITE'), ('EMPEROR SUITE', 'EMPEROR SUITE')], default='STANDARD', max_length=100),
        ),
    ]
