# Generated by Django 3.2 on 2022-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0042_alter_trip_stay_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stay_num_of_adults_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='stay_num_of_children_non_resident',
            field=models.IntegerField(default=0),
        ),
    ]
