# Generated by Django 3.2 on 2022-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0043_auto_20220630_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_groups_non_resident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_people_non_resident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_number_of_sessions_non_resident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
