# Generated by Django 3.2 on 2022-07-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0045_auto_20220701_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='stay_non_resident',
        ),
        migrations.AlterField(
            model_name='trip',
            name='stay_num_of_adults_non_resident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='stay_num_of_children_non_resident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
