# Generated by Django 3.2 on 2022-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0046_auto_20220711_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stay_is_a_home',
            field=models.BooleanField(default=False),
        ),
    ]
