# Generated by Django 3.2 on 2022-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0047_trip_stay_is_a_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='stay_is_a_home',
        ),
        migrations.AddField(
            model_name='trip',
            name='stay_home_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
