# Generated by Django 3.2 on 2022-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0048_auto_20220812_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='stay_home_capacity',
        ),
        migrations.AddField(
            model_name='trip',
            name='stay_home_is_non_resident',
            field=models.BooleanField(default=True),
        ),
    ]
