# Generated by Django 3.2 on 2022-08-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0049_auto_20220812_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='stay_home_is_non_resident',
        ),
    ]
