# Generated by Django 3.2 on 2022-08-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_flight_number_of_people'),
        ('trip', '0050_remove_trip_stay_home_is_non_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.flight'),
        ),
    ]
