# Generated by Django 3.2 on 2022-08-19 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0024_singletrip_countries_covered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0051_trip_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('starting_date', models.DateField(default=django.utils.timezone.now)),
                ('guests', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommended_trip.singletrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booked Trip',
                'verbose_name_plural': 'Booked Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
