# Generated by Django 3.2 on 2022-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0053_auto_20220822_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrip',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedtrip',
            name='reviewing',
            field=models.BooleanField(default=True),
        ),
    ]
