# Generated by Django 3.2 on 2022-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0054_auto_20220822_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrip',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
