# Generated by Django 3.2 on 2022-10-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0056_auto_20221015_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtrip',
            name='user',
        ),
    ]
