# Generated by Django 3.2 on 2022-10-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0057_remove_bookedtrip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrip',
            name='booking_request',
            field=models.BooleanField(default=False),
        ),
    ]
