# Generated by Django 3.2 on 2022-03-27 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_alter_stays_type_of_lodge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='type_of_lodge',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
    ]
