# Generated by Django 3.2 on 2022-03-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0005_alter_stays_type_of_lodge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
