# Generated by Django 3.2 on 2022-03-27 21:16

import core.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_alter_stays_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TYPE_OF_STAYS',
        ),
        migrations.AlterModelOptions(
            name='stays',
            options={'verbose_name': 'Stay'},
        ),
        migrations.AddField(
            model_name='stays',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=imagekit.models.fields.ProcessedImageField(upload_to=core.utils.lodge_image_thumbnail), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='location',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='num_of_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='pricing_per_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='pricing_per_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='pricing_per_whole_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('Per person', 'Per person'), ('Per room', 'Per room'), ('Whole place', 'Whole place')], max_length=100),
        ),
        migrations.AddField(
            model_name='stays',
            name='room_is_ensuite',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100),
        ),
        migrations.AddField(
            model_name='stays',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='type_of_boutique_hotel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='type_of_campsite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='type_of_house',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='type_of_unique_space',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='unique_about_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='type_of_lodge',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
    ]
