# Generated by Django 3.2 on 2022-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0007_auto_20220327_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER ROOM', 'PER ROOM'), ('WHOLE PLACE', 'WHOLE PLACE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stays',
            name='room_is_ensuite',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100),
        ),
    ]
