# Generated by Django 3.2 on 2022-03-27 23:25

import core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0009_auto_20220327_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to=core.utils.lodge_image_thumbnail),
            preserve_default=False,
        ),
    ]
