# Generated by Django 3.2 on 2022-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0010_stayimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
