# Generated by Django 3.2 on 2022-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0011_auto_20220330_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='type_of_stay',
            field=models.CharField(blank=True, choices=[('LODGE', 'LODGE'), ('HOUSE', 'HOUSE'), ('UNIQUE SPACE', 'UNIQUE SPACE'), ('CAMPSITE', 'CAMPSITE'), ('BOUTIQUE HOTEL', 'BOUTIQUE HOTEL')], max_length=100),
        ),
    ]
