# Generated by Django 3.2 on 2022-03-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0012_stays_type_of_stay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stays',
            old_name='type_of_boutique_hotel',
            new_name='best_describes_boutique_hotel',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='type_of_campsite',
            new_name='best_describes_campsite',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='type_of_house',
            new_name='best_describes_house',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='type_of_lodge',
            new_name='best_describes_lodge',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='type_of_unique_space',
            new_name='best_describes_unique_space',
        ),
    ]
