# Generated by Django 3.2 on 2022-03-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0015_auto_20220330_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stays',
            name='room_is_ensuite',
            field=models.BooleanField(default=False),
        ),
    ]
