# Generated by Django 3.2 on 2022-03-31 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0016_auto_20220330_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
