# Generated by Django 3.2 on 2022-03-31 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0019_auto_20220331_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, default=list, help_text="Separate each amenities by using ' , '. Eg Swimming Pool, Hot tub", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stays',
            name='name',
            field=models.CharField(help_text='If no name, enter a short description of the accommodation. Eg A lovely place located at the lake side', max_length=250),
        ),
    ]
