# Generated by Django 3.2 on 2022-04-02 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0020_auto_20220331_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stays',
            old_name='num_of_capacity',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='stays',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stays',
            name='name',
            field=models.CharField(help_text='If no name, enter a short description of the accommodation. Eg A lovely place located at the lake side', max_length=100, verbose_name='Name or description'),
        ),
    ]
