# Generated by Django 3.2 on 2022-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0021_auto_20220402_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
