# Generated by Django 3.2 on 2022-04-12 22:34

from django.db import migrations


class Migration(migrations.Migration):
    def custom_task(self, schema_editor):
        Stays = self.get_model("lodging", "Stays")

        for stay in Stays.objects.all():
            stay.price = (
                stay.pricing_per_person
                or stay.pricing_per_room
                or stay.pricing_per_whole_place
            )
            stay.save()

    dependencies = [
        ("lodging", "0022_stays_price"),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop),
    ]
