# Generated by Django 3.2 on 2022-04-20 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0024_auto_20220412_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lodging.stays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
