# Generated by Django 3.2 on 2022-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0028_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
