# Generated by Django 3.2 on 2022-04-22 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0030_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='essential_information',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="Separate each essential information by using ' , '. Eg Covid-19 compliance", null=True, size=None),
        ),
    ]
