# Generated by Django 3.2 on 2022-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0033_auto_20220427_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
