# Generated by Django 3.2 on 2022-04-27 14:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0034_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 14, 26, 32, 784063)),
        ),
    ]
