# Generated by Django 3.2 on 2022-04-27 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0035_auto_20220427_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 14, 30, 26, 361171, tzinfo=utc)),
        ),
    ]
