# Generated by Django 3.2 on 2022-04-27 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0038_alter_order_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 14, 37, 13, 651450, tzinfo=utc)),
        ),
    ]
