# Generated by Django 3.2 on 2022-04-29 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0042_alter_order_from_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateField(default=datetime.date(2022, 4, 30)),
        ),
    ]
