# Generated by Django 3.2 on 2022-05-20 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0045_auto_20220518_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='starting_point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 23)),
        ),
    ]
