# Generated by Django 3.2 on 2022-05-25 14:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0050_auto_20220525_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 14, 37, 34, 366397)),
        ),
    ]
