# Generated by Django 3.2 on 2022-05-25 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_order_to_date'),
        ('transport', '0006_auto_20220524_1820'),
        ('lodging', '0052_alter_order_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activities'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='lodging.stays'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 22, 36, 26, 624611, tzinfo=utc)),
        ),
    ]
