# Generated by Django 3.2 on 2022-05-27 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20220524_1820'),
        ('activities', '0014_alter_order_to_date'),
        ('lodging', '0055_auto_20220526_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activities'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='lodging.stays'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 15, 38, 163219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport', to='transport.transportation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_back', to='transport.transportation'),
        ),
    ]
