# Generated by Django 3.2 on 2022-06-09 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0069_auto_20220608_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num_of_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='num_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='num_of_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='num_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stays',
            name='delux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='delux_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='delux_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='standard_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_delux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_delux_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_delux_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 7, 54, 10, 390603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 7, 54, 10, 390603, tzinfo=utc)),
        ),
    ]
