# Generated by Django 3.2 on 2022-06-09 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0070_auto_20220609_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 8, 5, 56, 440794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 8, 5, 56, 440794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stays',
            name='standard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='standard_capacity',
            field=models.IntegerField(default=2),
        ),
    ]
