# Generated by Django 3.2 on 2022-06-09 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0071_auto_20220609_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stays',
            old_name='delux',
            new_name='deluxe',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='delux_capacity',
            new_name='deluxe_capacity',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='delux_price',
            new_name='deluxe_price',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='super_delux',
            new_name='super_deluxe',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='super_delux_capacity',
            new_name='super_deluxe_capacity',
        ),
        migrations.RenameField(
            model_name='stays',
            old_name='super_delux_price',
            new_name='super_deluxe_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='plan',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPLE ROOM', 'TRIPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM')], default='STANDARD', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPLE ROOM', 'TRIPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM')], default='STANDARD', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 10, 40, 46, 51431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 10, 40, 46, 51431, tzinfo=utc)),
        ),
    ]
