# Generated by Django 3.2 on 2022-06-10 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0074_auto_20220610_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='family_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='plan',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPLE ROOM', 'TRIPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM'), ('FAMILY', 'FAMILY')], default='STANDARD', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 4, 11, 3, 226250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DELUXE', 'DELUXE'), ('SUPER DELUXE', 'SUPER DELUXE'), ('STUDIO', 'STUDIO'), ('DOUBLE ROOM', 'DOUBLE ROOM'), ('TRIPLE ROOM', 'TRIPLE ROOM'), ('QUAD ROOM', 'QUAD ROOM'), ('KING ROOM', 'KING ROOM'), ('QUEEN ROOM', 'QUEEN ROOM'), ('TWIN ROOM', 'TWIN ROOM'), ('FAMILY', 'FAMILY')], default='STANDARD', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 4, 11, 3, 226250, tzinfo=utc)),
        ),
    ]
