# Generated by Django 3.2 on 2022-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0095_auto_20220616_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='starting_point',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport_back',
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
