# Generated by Django 3.2 on 2022-06-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0096_auto_20220617_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='likes',
            field=models.ManyToManyField(related_name='stay_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SaveStays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_stays', to='lodging.stays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
