# Generated by Django 3.2 on 2022-06-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0098_remove_stays_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='best_describes_boutique_hotel',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='best_describes_campsite',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='best_describes_house',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='best_describes_lodge',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='best_describes_unique_space',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='essential_information',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='room_is_ensuite',
        ),
    ]
