# Generated by Django 3.2 on 2022-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0099_auto_20220629_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
