# Generated by Django 3.2 on 2022-06-29 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0100_stays_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='included',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="included in this package ' , '. Eg Pool", null=True, size=None),
        ),
    ]
