# Generated by Django 3.2 on 2022-06-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0101_stays_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='Salon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='barber_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='beauty_salon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='conference_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='ensuite_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='facts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="Experiences included in this package ' , '", null=True, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='firewood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='other_amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="included in this package ' , '.", null=True, size=None),
        ),
        migrations.AddField(
            model_name='stays',
            name='purified_drinking_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stays',
            name='damage_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='refund_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
