# Generated by Django 3.2 on 2022-06-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0102_auto_20220629_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='Salon',
        ),
    ]
