# Generated by Django 3.2 on 2022-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0104_auto_20220629_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='pricing_type',
            field=models.CharField(choices=[('REASONABLE', 'REASONABLE'), ('MID-RANGE', 'MID-RANGE'), ('HIGH-END', 'HIGH-END')], default='REASONABLE', max_length=100),
        ),
    ]
