# Generated by Django 3.2 on 2022-06-29 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0106_auto_20220629_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencesincluded',
            options={'verbose_name': 'Experience Included', 'verbose_name_plural': 'Experiences Included'},
        ),
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name': 'Fact', 'verbose_name_plural': 'Facts'},
        ),
        migrations.AlterModelOptions(
            name='inclusions',
            options={'verbose_name': 'Inclusion', 'verbose_name_plural': 'Inclusions'},
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='deluxe_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='double_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='emperor_suite_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='family_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='king_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='presidential_suite_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='quad_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='queen_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='studio_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='super_deluxe_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='tripple_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='twin_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='other_amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="Separate each amenities by using ' , '", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stays',
            name='type_of_stay',
            field=models.CharField(blank=True, choices=[('LODGE', 'LODGE'), ('HOUSE', 'HOUSE'), ('UNIQUE SPACE', 'UNIQUE SPACE'), ('CAMPSITE', 'CAMPSITE'), ('TENTED CAMP', 'TENTED CAMP'), ('BOUTIQUE HOTEL', 'BOUTIQUE HOTEL'), ('WEEKEND GETAWAY', 'WEEKEND GETAWAY'), ('ROMANTIC GETAWAY', 'ROMANTIC GETAWAY'), ('GROUP GETAWAY', 'GROUP GETAWAY'), ('CONSERVANCY', 'CONSERVANCY'), ('NATIONAL PARK/GAME RESERVES', 'NATIONAL PARK/GAME RESERVES'), ('COZY PLACE', 'COZY PLACE'), ('LAKEFRONT', 'LAKEFRONT'), ('BEACHFRONT', 'BEACHFRONT'), ('LUXURIOUS', 'LUXURIOUS'), ('BEAUTIFUL VIEW', 'BEAUTIFUL VIEW'), ('OFF-GRID', 'OFF-GRID'), ('ECO-STAY', 'ECO-STAY'), ('QUIRKY', 'QUIRKY'), ('TRADITIONAL', 'TRADITIONAL'), ('MANSIONS', 'MANSIONS'), ('OVER-WATER', 'OVER-WATER'), ('UNIQUE EXPERIENCES', 'UNIQUE EXPERIENCES'), ('STUNNING ARCHITECTURE', 'STUNNING ARCHITECTURE'), ('HONEYMOON SPOT', 'HONEYMOON SPOT'), ('RIVERFRONT', 'RIVERFRONT'), ('PRIVATE HOUSE', 'PRIVATE HOUSE'), ('RESORT', 'RESORT')], max_length=100),
        ),
    ]
