# Generated by Django 3.2 on 2022-06-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0108_auto_20220629_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='cancellation_policy_by_provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='damage_policy_by_provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='health_and_safety_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
