# Generated by Django 3.2 on 2022-06-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0109_auto_20220629_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_children_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_children_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='executive_suite_room_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='type_of_stay',
            field=models.CharField(blank=True, choices=[('LODGE', 'LODGE'), ('HOUSE', 'HOUSE'), ('UNIQUE SPACE', 'UNIQUE SPACE'), ('CAMPSITE', 'CAMPSITE'), ('TENTED CAMP', 'TENTED CAMP'), ('BOUTIQUE HOTEL', 'BOUTIQUE HOTEL'), ('WEEKEND GETAWAY', 'WEEKEND GETAWAY'), ('ROMANTIC GETAWAY', 'ROMANTIC GETAWAY'), ('GROUP GETAWAY', 'GROUP GETAWAY'), ('CONSERVANCY', 'CONSERVANCY'), ('NATIONAL PARK/GAME RESERVES', 'NATIONAL PARK/GAME RESERVES'), ('COZY PLACE', 'COZY PLACE'), ('LAKEFRONT', 'LAKEFRONT'), ('BEACHFRONT', 'BEACHFRONT'), ('LUXURIOUS', 'LUXURIOUS'), ('BEAUTIFUL VIEW', 'BEAUTIFUL VIEW'), ('OFF-GRID', 'OFF-GRID'), ('ECO-STAY', 'ECO-STAY'), ('QUIRKY', 'QUIRKY'), ('TRADITIONAL', 'TRADITIONAL'), ('MANSIONS', 'MANSIONS'), ('OVER-WATER', 'OVER-WATER'), ('UNIQUE EXPERIENCES', 'UNIQUE EXPERIENCES'), ('STUNNING ARCHITECTURE', 'STUNNING ARCHITECTURE'), ('HONEYMOON SPOT', 'HONEYMOON SPOT'), ('RIVERFRONT', 'RIVERFRONT'), ('PRIVATE HOUSE', 'PRIVATE HOUSE'), ('RESORT', 'RESORT'), ('FARMSTAY', 'FARMSTAY')], max_length=100),
        ),
    ]
