# Generated by Django 3.2 on 2022-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0110_auto_20220629_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='non_resident',
        ),
        migrations.RemoveField(
            model_name='order',
            name='non_resident',
        ),
        migrations.AddField(
            model_name='cart',
            name='num_of_adults_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='num_of_children_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='num_of_adults_non_resident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='num_of_children_non_resident',
            field=models.IntegerField(default=0),
        ),
    ]
