# Generated by Django 3.2 on 2022-07-02 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0112_auto_20220701_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Separate each tags by using ' , '", null=True, size=None),
        ),
    ]
