# Generated by Django 3.2 on 2022-07-04 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0113_stays_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrasIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_included', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Extra Included',
                'verbose_name_plural': 'Extras Included',
            },
        ),
    ]
