# Generated by Django 3.2 on 2022-07-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0114_extrasincluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_children_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_children_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_child_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_single_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_teen_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='conservation_or_park_teen_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
