# Generated by Django 3.2 on 2022-07-04 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0115_auto_20220704_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='property_name',
            field=models.CharField(blank=True, help_text='If no name, enter a short description of the accommodation. Eg A lovely place located at the lake side', max_length=250, null=True, verbose_name='Name or description'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='name',
            field=models.CharField(help_text='If no name, enter a short description of the accommodation. Eg A lovely place located at the lake side', max_length=500, verbose_name='Name or description'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Separate each tag by using ' , '", null=True, size=None),
        ),
    ]
