# Generated by Django 3.2 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0116_auto_20220704_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
