# Generated by Django 3.2 on 2022-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0117_stays_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='property_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
