# Generated by Django 3.2 on 2022-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0118_alter_stays_property_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stays',
            options={'verbose_name': 'Stay', 'verbose_name_plural': 'Stays'},
        ),
    ]
