# Generated by Django 3.2 on 2022-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0119_alter_stays_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
