# Generated by Django 3.2 on 2022-07-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0120_stays_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='test',
        ),
    ]
