# Generated by Django 3.2 on 2022-08-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0122_auto_20220809_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrasincluded',
            options={'verbose_name': 'Extra', 'verbose_name_plural': 'Extras'},
        ),
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name': 'Amenties(Quick Fact)', 'verbose_name_plural': 'Amenties(Quick Facts)'},
        ),
        migrations.AlterModelOptions(
            name='inclusions',
            options={'verbose_name': 'Included Activity', 'verbose_name_plural': 'Included Activities'},
        ),
    ]
