# Generated by Django 3.2 on 2022-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0123_auto_20220809_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='per_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stays',
            name='per_house_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='per_house_price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
