# Generated by Django 3.2 on 2022-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0124_auto_20220811_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stay_is_a_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stay_is_a_home',
            field=models.BooleanField(default=False),
        ),
    ]
