# Generated by Django 3.2 on 2022-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0133_alter_stays_type_of_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='beachfront',
            field=models.BooleanField(default=False),
        ),
    ]
