# Generated by Django 3.2 on 2022-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0135_stays_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='event_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='is_an_event',
            field=models.BooleanField(default=False),
        ),
    ]
