# Generated by Django 3.2 on 2022-09-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0138_typeofroomsimages_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='bus_transfer_price',
            field=models.FloatField(blank=True, help_text='Add if bus service is available', null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='car_transfer_price',
            field=models.FloatField(blank=True, help_text='Add if car service is available', null=True),
        ),
        migrations.AddField(
            model_name='typeofrooms',
            name='available_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeofrooms',
            name='sleeps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeofrooms',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_rooms', to='lodging.stays'),
        ),
    ]
