# Generated by Django 3.2 on 2022-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0139_auto_20220918_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event booking', 'verbose_name_plural': 'Event bookings'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='event',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='transport',
            field=models.CharField(blank=True, choices=[(0, 'No Transport'), (1, 'Car'), (2, 'Bus')], max_length=100),
        ),
    ]
