# Generated by Django 3.2 on 2022-09-19 00:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0140_auto_20220919_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
