# Generated by Django 3.2 on 2022-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0142_event_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrooms',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
