# Generated by Django 3.2 on 2022-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0143_typeofrooms_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrooms',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
