# Generated by Django 3.2 on 2022-09-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0144_typeofrooms_is_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='event_price',
        ),
    ]
