# Generated by Django 3.2 on 2022-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0145_remove_stays_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payment confirmed'),
        ),
    ]
