# Generated by Django 3.2 on 2022-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0147_stays_distance_from_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='bus_transfer_end_location',
            field=models.CharField(blank=True, help_text='Add if bus service is available', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='bus_transfer_starting_location',
            field=models.CharField(blank=True, help_text='Add if bus service is available', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stays',
            name='car_transfer_end_location',
            field=models.CharField(blank=True, help_text='Add if car service is available', max_length=250, null=True, verbose_name='Van Transfer End Location'),
        ),
        migrations.AddField(
            model_name='stays',
            name='car_transfer_starting_location',
            field=models.CharField(blank=True, help_text='Add if car service is available', max_length=250, null=True, verbose_name='Van Transfer Starting Location'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='car_transfer_price',
            field=models.FloatField(blank=True, help_text='Add if car service is available', null=True, verbose_name='Van Transfer Price'),
        ),
    ]
