# Generated by Django 3.2 on 2022-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0148_auto_20220921_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='passengers',
            field=models.IntegerField(default=0),
        ),
    ]
