# Generated by Django 3.2 on 2022-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0149_event_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_room',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
