# Generated by Django 3.2 on 2022-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0150_event_type_of_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrooms',
            name='is_tented_camp',
            field=models.BooleanField(default=False),
        ),
    ]
