# Generated by Django 3.2 on 2022-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0151_typeofrooms_is_tented_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='bus_transfer_end_location',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='bus_transfer_starting_location',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='car_transfer_end_location',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='car_transfer_starting_location',
        ),
        migrations.AddField(
            model_name='stays',
            name='bus_transfer_text_location',
            field=models.CharField(blank=True, help_text='Add if bus service is available', max_length=250, null=True, verbose_name='Bus Transfer Text Location'),
        ),
        migrations.AddField(
            model_name='stays',
            name='car_transfer_text_location',
            field=models.CharField(blank=True, help_text='Add if car service is available', max_length=250, null=True, verbose_name='Van Transfer Text Location'),
        ),
    ]
