# Generated by Django 3.2 on 2022-09-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0152_auto_20220925_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrooms',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
