# Generated by Django 3.2 on 2022-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0154_stays_has_min_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='date_starts_from_ninth',
            field=models.BooleanField(default=False),
        ),
    ]
