# Generated by Django 3.2 on 2022-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0155_stays_date_starts_from_ninth'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrooms',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
