# Generated by Django 3.2 on 2022-10-06 13:21

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0156_typeofrooms_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('type_of_transport', models.CharField(blank=True, max_length=300, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('message', models.TextField(blank=True, null=True)),
                ('passengers', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False, verbose_name='payment confirmed')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event Transport booking',
                'verbose_name_plural': 'Event Transport bookings',
            },
        ),
    ]
