# Generated by Django 3.2 on 2022-12-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0162_alter_stays_unavailable_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
