# Generated by Django 3.2 on 2022-12-19 21:20

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0163_stays_in_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_private_safari', models.BooleanField(default=False)),
                ('is_shared_safari', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type of Option',
                'verbose_name_plural': 'Type of Options',
            },
        ),
        migrations.AddField(
            model_name='stays',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TypeOfOptionsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=core.utils.lodge_image_thumbnail)),
                ('type_of_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_option_images', to='lodging.typeofoptions')),
            ],
            options={
                'verbose_name': 'Type of Option Image',
                'verbose_name_plural': 'Type of Option Images',
            },
        ),
        migrations.AddField(
            model_name='typeofoptions',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_options', to='lodging.stays'),
        ),
    ]
