# Generated by Django 3.2 on 2022-12-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0167_auto_20221220_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatesafari',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='sharedsafari',
            name='short_description',
        ),
        migrations.AddField(
            model_name='privatesafari',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedsafari',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
