# Generated by Django 3.2 on 2023-01-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0169_auto_20230111_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinclusive',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatesafari',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sharedsafari',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
