# Generated by Django 3.2 on 2023-01-11 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0170_auto_20230111_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgePackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('type_of_package', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('message', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False, verbose_name='payment confirmed')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodge_package_order', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Lodge package booking',
                'verbose_name_plural': 'Lodge package bookings',
            },
        ),
    ]
