# Generated by Django 3.2 on 2023-01-20 10:26

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0171_lodgepackagebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_option', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Other Option',
                'verbose_name_plural': 'Other Options',
            },
        ),
        migrations.CreateModel(
            name='OtherOptionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=core.utils.lodge_image_thumbnail)),
                ('main', models.BooleanField(default=False)),
                ('other_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_option_images', to='lodging.otheroption')),
            ],
            options={
                'verbose_name': 'Other Option Image',
                'verbose_name_plural': 'Other Option Images',
            },
        ),
    ]
