# Generated by Django 3.2 on 2023-01-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0173_lodgepackagebookinginstallment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgepackagebookinginstallment',
            options={'verbose_name': 'Lodge package booking Installment', 'verbose_name_plural': 'Lodge package bookings Installment'},
        ),
    ]
