# Generated by Django 3.2 on 2023-01-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0175_alter_otheroption_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheroption',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_options', to='lodging.stays'),
        ),
    ]
