# Generated by Django 3.2 on 2023-01-28 22:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0177_stays_is_kaleidoscope_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('num_of_available_rooms', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_availabilities', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Room availability',
                'verbose_name_plural': 'Room availabilities',
            },
        ),
    ]
