# Generated by Django 3.2 on 2023-01-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0178_roomavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailability',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
