# Generated by Django 3.2 on 2023-01-29 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0179_alter_roomavailability_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomavailability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='stay',
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
            },
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_availabilities', to='lodging.roomtype'),
            preserve_default=False,
        ),
    ]
