# Generated by Django 3.2 on 2023-02-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0181_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='num_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
