# Generated by Django 3.2 on 2023-02-10 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0183_auto_20230210_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailabilityResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('num_of_available_rooms', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident_availabilities', to='lodging.roomtype')),
            ],
            options={
                'verbose_name': 'Room availability Resident',
                'verbose_name_plural': 'Room availabilities Resident',
            },
        ),
        migrations.CreateModel(
            name='RoomAvailabilityNonResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('num_of_available_rooms', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_non_resident_availabilities', to='lodging.roomtype')),
            ],
            options={
                'verbose_name': 'Room availability Non-Resident',
                'verbose_name_plural': 'Room availabilities Non-Resident',
            },
        ),
    ]
