# Generated by Django 3.2 on 2023-02-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0184_roomavailabilitynonresident_roomavailabilityresident'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailabilityResidentGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_availability_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident_guest_availabilities', to='lodging.roomavailabilityresident')),
            ],
            options={
                'verbose_name': 'Room availability Resident Guest',
                'verbose_name_plural': 'Room availabilities Resident Guest',
            },
        ),
        migrations.CreateModel(
            name='RoomAvailabilityNonResidentGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_availability_non_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_non_resident_guest_availabilities', to='lodging.roomavailabilitynonresident')),
            ],
            options={
                'verbose_name': 'Room availability Non-Resident Guest',
                'verbose_name_plural': 'Room availabilities Non-Resident Guest',
            },
        ),
    ]
