# Generated by Django 3.2 on 2023-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0185_roomavailabilitynonresidentguest_roomavailabilityresidentguest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailabilitynonresidentguest',
            name='name',
            field=models.CharField(blank=True, choices=[('ADULT SINGLE', 'ADULT SINGLE'), ('ADULT DOUBLE', 'ADULT DOUBLE'), ('ADULT TRIPLE', 'ADULT TRIPLE'), ('CHILD SINGLE', 'CHILD SINGLE'), ('CHILD DOUBLE', 'CHILD DOUBLE'), ('CHILD TRIPLE', 'CHILD TRIPLE'), ('INFANT', 'INFANT')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='roomavailabilityresidentguest',
            name='name',
            field=models.CharField(blank=True, choices=[('ADULT SINGLE', 'ADULT SINGLE'), ('ADULT DOUBLE', 'ADULT DOUBLE'), ('ADULT TRIPLE', 'ADULT TRIPLE'), ('CHILD SINGLE', 'CHILD SINGLE'), ('CHILD DOUBLE', 'CHILD DOUBLE'), ('CHILD TRIPLE', 'CHILD TRIPLE'), ('INFANT', 'INFANT')], max_length=120, null=True),
        ),
    ]
