# Generated by Django 3.2 on 2023-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0186_auto_20230215_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailabilitynonresidentguest',
            name='age_group',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='roomavailabilityresidentguest',
            name='age_group',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
