# Generated by Django 3.2 on 2023-02-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0187_auto_20230216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='child_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='infant_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResidentOtherFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('PARK FEES', 'PARK FEES'), ('CONSERVANCY/BEDNIGHT FEES', 'CONSERVANCY/BEDNIGHT FEES'), ('CONTRIBUTION', 'CONTRIBUTION')], max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_availability_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_other_fees', to='lodging.roomavailabilityresident')),
            ],
            options={
                'verbose_name': 'Resident Other Fees',
                'verbose_name_plural': 'Resident Other Fees',
            },
        ),
        migrations.CreateModel(
            name='NonResidentOtherFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('PARK FEES', 'PARK FEES'), ('CONSERVANCY/BEDNIGHT FEES', 'CONSERVANCY/BEDNIGHT FEES'), ('CONTRIBUTION', 'CONTRIBUTION')], max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_availability_non_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_resident_other_fees', to='lodging.roomavailabilitynonresident')),
            ],
            options={
                'verbose_name': 'Non-Resident Other Fees',
                'verbose_name_plural': 'Non-Resident Other Fees',
            },
        ),
    ]
