# Generated by Django 3.2 on 2023-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0188_auto_20230219_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonresidentotherfees',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='residentotherfees',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
