# Generated by Django 3.2 on 2023-02-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0189_auto_20230220_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='is_partner_property',
            field=models.BooleanField(default=False),
        ),
    ]
