# Generated by Django 3.2 on 2023-02-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0190_stays_is_partner_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFeesResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fees_resident', to='lodging.roomtype')),
            ],
            options={
                'verbose_name': 'Resident Other Fees',
                'verbose_name_plural': 'Resident Other Fees',
            },
        ),
        migrations.CreateModel(
            name='OtherFeesNonResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.FloatField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fees_non_resident', to='lodging.roomtype')),
            ],
            options={
                'verbose_name': 'Non-Resident Other Fees',
                'verbose_name_plural': 'Non-Resident Other Fees',
            },
        ),
    ]
