# Generated by Django 3.2 on 2023-02-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0191_otherfeesnonresident_otherfeesresident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfeesnonresident',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='otherfeesresident',
            name='room_type',
        ),
        migrations.AddField(
            model_name='otherfeesnonresident',
            name='stay',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='other_fees_non_resident', to='lodging.stays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherfeesresident',
            name='stay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_fees_resident', to='lodging.stays'),
            preserve_default=False,
        ),
    ]
