# Generated by Django 3.2 on 2023-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0192_auto_20230223_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfeesnonresident',
            name='nonresident_fee_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER PERSON PER NIGHT', 'PER PERSON PER NIGHT'), ('WHOLE GROUP', 'WHOLE GROUP')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otherfeesresident',
            name='resident_fee_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER PERSON PER NIGHT', 'PER PERSON PER NIGHT'), ('WHOLE GROUP', 'WHOLE GROUP')], max_length=120, null=True),
        ),
    ]
