# Generated by Django 3.2 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0194_auto_20230301_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeesnonresident',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeesresident',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT')], max_length=120, null=True),
        ),
    ]
