# Generated by Django 3.2 on 2023-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0195_auto_20230301_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeesnonresident',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT')], default='ADULT', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeesnonresident',
            name='nonresident_fee_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER PERSON PER NIGHT', 'PER PERSON PER NIGHT'), ('WHOLE GROUP', 'WHOLE GROUP')], default='PER PERSON', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeesresident',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT')], default='ADULT', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeesresident',
            name='resident_fee_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER PERSON PER NIGHT', 'PER PERSON PER NIGHT'), ('WHOLE GROUP', 'WHOLE GROUP')], default='PER PERSON', max_length=120, null=True),
        ),
    ]
