# Generated by Django 3.2 on 2023-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0196_auto_20230301_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='sheety_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
