# Generated by Django 3.2 on 2023-04-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0197_stays_sheety_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfeesnonresident',
            name='is_park_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherfeesresident',
            name='is_park_fee',
            field=models.BooleanField(default=False),
        ),
    ]
