# Generated by Django 3.2 on 2023-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0198_auto_20230406_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='package',
            field=models.CharField(choices=[('ALL INCLUSIVE', 'ALL INCLUSIVE'), ('GAME PACKAGE', 'GAME PACKAGE'), ('FULL BOARD', 'FULL BOARD'), ('HALF BOARD', 'HALF BOARD'), ('BED AND BREAKFAST', 'BED AND BREAKFAST')], default='ALL INCLUSIVE', max_length=120),
        ),
    ]
