# Generated by Django 3.2 on 2023-04-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0199_roomtype_package"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS lodging_activityfee;"),
    ]
