# Generated by Django 3.2 on 2023-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0201_activityfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfee',
            name='price_type',
            field=models.CharField(blank=True, choices=[('PER PERSON', 'PER PERSON'), ('PER PERSON PER NIGHT', 'PER PERSON PER NIGHT'), ('WHOLE GROUP', 'WHOLE GROUP')], default='PER PERSON', max_length=120, null=True),
        ),
    ]
