# Generated by Django 3.2 on 2023-04-25 12:31

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0203_auto_20230414_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='lodge_price_data_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.lodge_price_data_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
