# Generated by Django 3.2 on 2023-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0207_activityfee_nonresident_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfee',
            name='nonresident_price',
        ),
        migrations.AddField(
            model_name='activityfee',
            name='resident_price',
            field=models.FloatField(default=0, help_text='for resident'),
        ),
        migrations.AlterField(
            model_name='activityfee',
            name='price',
            field=models.FloatField(default=0, help_text='for non-resident'),
        ),
    ]
