# Generated by Django 3.2 on 2023-06-08 00:27

import core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0208_auto_20230607_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=core.utils.activity_fees_image_thumbnail),
        ),
    ]
