# Generated by Django 3.2 on 2023-06-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0209_alter_activityfee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailabilitynonresidentguest',
            name='season',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='roomavailabilityresidentguest',
            name='season',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
