# Generated by Django 3.2 on 2023-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0210_auto_20230612_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stays',
            name='name',
            field=models.CharField(blank=True, help_text='If no name, enter a short description of the accommodation. Eg A lovely place located at the lake side', max_length=500, null=True, verbose_name='Name or description'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('REASONABLE', 'REASONABLE'), ('MID-RANGE', 'MID-RANGE'), ('HIGH-END', 'HIGH-END')], default='REASONABLE', max_length=100, null=True),
        ),
    ]
