# Generated by Django 3.2 on 2023-06-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0211_auto_20230617_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('resident_adult_price', models.FloatField(default=0)),
                ('resident_child_price', models.FloatField(default=0)),
                ('resident_teen_price', models.FloatField(default=0)),
                ('non_resident_adult_price', models.FloatField(default=0)),
                ('non_resident_child_price', models.FloatField(default=0)),
                ('non_resident_teen_price', models.FloatField(default=0)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_fees', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Park Fees',
                'verbose_name_plural': 'Park Fees',
            },
        ),
    ]
