# Generated by Django 3.2 on 2023-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0212_parkfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
