# Generated by Django 3.2 on 2023-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0214_alter_roomtype_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
