# Generated by Django 3.2 on 2023-07-22 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0215_alter_roomtype_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='annonymous_added_to_calculate',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='user_added_to_calculate',
        ),
        migrations.AddField(
            model_name='stays',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
