# Generated by Django 3.2 on 2023-08-04 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0216_auto_20230722_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access', to='lodging.stays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Access',
                'verbose_name_plural': 'Agent Access',
            },
        ),
    ]
