# Generated by Django 3.2 on 2023-08-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0218_auto_20230804_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='agents',
        ),
    ]
