# Generated by Django 3.2 on 2023-08-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0219_remove_stays_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='agents', to='lodging.Agents'),
        ),
    ]
