# Generated by Django 3.2 on 2023-08-04 04:03

from django.db import migrations

def update_agents_field(apps, schema_editor):
    Stays = apps.get_model('lodging', 'Stays')
    Agents = apps.get_model('lodging', 'Agents')

    for obj in Stays.objects.all():
        agents_access_objects = Agents.objects.filter(stay=obj)
        obj.agents.set(agents_access_objects)


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0220_stays_agents'),
    ]

    operations = [
        migrations.RunPython(update_agents_field),
    ]
