# Generated by Django 3.2 on 2023-08-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0222_agents_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsByEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_email', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Agent By Email',
                'verbose_name_plural': 'Agents By Email',
            },
        ),
        migrations.AddField(
            model_name='stays',
            name='agents_by_email',
            field=models.ManyToManyField(blank=True, related_name='agents_by_email', to='lodging.AgentsByEmail'),
        ),
    ]
