# Generated by Django 3.2 on 2023-08-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0224_rename_accepted_agentsbyemail_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsbyemail',
            name='approved',
        ),
    ]
