# Generated by Django 3.2 on 2023-08-24 23:08

from django.db import migrations, models
import django.contrib.postgres.fields

def migrate_email_to_array(apps, schema_editor):
    YourModel = apps.get_model('lodging', 'Stays')
    for instance in YourModel.objects.all():
        instance.contact_emails = [instance.contact_email] if instance.contact_email else []
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0225_remove_agentsbyemail_approved'),
    ]

    operations = [
        migrations.RunPython(migrate_email_to_array),
    ]

