# Generated by Django 3.2 on 2023-08-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0226_auto_20230824_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_access', to='lodging.stays')),
            ],
            options={
                'verbose_name': 'Property Access',
                'verbose_name_plural': 'Property Access',
            },
        ),
        migrations.AddField(
            model_name='stays',
            name='property_access',
            field=models.ManyToManyField(blank=True, related_name='property_access', to='lodging.PropertyAccess'),
        ),
    ]
