# Generated by Django 3.2 on 2023-08-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0227_auto_20230825_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='property_access',
        ),
        migrations.AddField(
            model_name='stays',
            name='property_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_access', to='lodging.propertyaccess'),
        ),
    ]
