# Generated by Django 3.2 on 2023-08-25 11:35

from django.db import migrations
from lodging.models import PropertyAccess, Stays

def migrate_email_to_property_access(apps, schema_editor):
    YourModel = apps.get_model('lodging', 'Stays')
    for instance in YourModel.objects.all():
        stay = Stays.objects.get(pk=instance.pk)
        PropertyAccess.objects.create(
            email=instance.contact_email,
            stay=stay
        )
        

class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0228_auto_20230825_1142'),
    ]

    operations = [
        migrations.RunPython(migrate_email_to_property_access),
    ]
