# Generated by Django 3.2 on 2023-08-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0229_auto_20230825_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='property_access',
        ),
    ]
