# Generated by Django 3.2 on 2023-08-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0230_remove_stays_property_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaccess',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_access', to='lodging.stays'),
        ),
    ]
