# Generated by Django 3.2 on 2023-09-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0231_alter_propertyaccess_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsbyemail',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentsbyemail',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
