# Generated by Django 3.2 on 2023-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0233_agentdiscountrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stays',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='stays',
            name='agents_by_email',
        ),
        migrations.AddField(
            model_name='agents',
            name='contract_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
