# Generated by Django 3.2 on 2023-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0234_auto_20230911_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsbyemail',
            name='contract_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
