# Generated by Django 3.2 on 2023-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0236_auto_20230911_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdiscountrate',
            name='resident_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='resident_contract_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsbyemail',
            name='resident_contract_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
