# Generated by Django 3.2 on 2022-04-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
