# Generated by Django 3.2 on 2022-10-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
