# Generated by Django 3.2 on 2023-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_is_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
