# Generated by Django 3.2 on 2023-09-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230901_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="This is either a user's email or aws cognito user id", max_length=255, unique=True, verbose_name='Email or Username'),
        ),
    ]
