# Generated by Django 3.2 on 2023-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Primary Email'),
        ),
    ]
