from django.urls import path
from .views import *


urlpatterns = [
    path("stays/", StaysListView.as_view(), name="stays-list"),
    path(
        "stays/<slug>/update-agents/",
        UserStayEmailUpdateAgentsView.as_view(),
        name="stays-update-agents",
    ),
    path(
        "stays/<slug>/agent-discounts/",
        AgentDiscountRateListCreateView.as_view(),
        name="agent-discount-rate-list-create",
    ),
    path(
        "stays/<slug>/agent-discounts/<int:pk>/",
        AgentDiscountRateDetailView.as_view(),
        name="agent-discount-rate-detail-view",
    ),
    path(
        "stays/<slug>/update-agents-email/",
        AddAgentToStayView.as_view(),
        name="stays-update-agents-email",
    ),
    path(
        "stays/<slug>/update-property-access/",
        PropertyAccessCreateView.as_view(),
        name="stays-update-property-access",
    ),
    path(
        "stays/<slug>/update-agents-with-file/",
        UserStayEmailUpdateAgentsWithFileView.as_view(),
        name="stays-update-agents-with-file",
    ),
    path(
        "remove-agent/<int:pk>/",
        UserStayEmailRemoveAgentsView.as_view(),
        name="stays-remove-agent",
    ),
    path(
        "add-agent-from-invite/",
        AddAgentFromInviteView.as_view(),
        name="add-agent-from-invite",
    ),
    path(
        "accept-property-invite/",
        AcceptPropertyInviteView.as_view(),
        name="accept-property-invite",
    ),
    path(
        "highlighted-stays/",
        HighlightedStaysListView.as_view(),
        name="highlighted-stays-list",
    ),
    path(
        "highlighted-detail-stays/",
        HiglighedDetailStayListView.as_view(),
        name="highlighted-detail-stays-list",
    ),
    path(
        "highlighted-detail-stays/<slug>/",
        HiglighedDetailStayRetrieveView.as_view(),
        name="highlighted-detail-stays-retrieve",
    ),
    path(
        "highlighted-stays/<slug>/",
        HighlightedStaysDetailView.as_view(),
        name="highlighted-stays-detail",
    ),
    path("user-stays/", UserStays.as_view(), name="user-stays-list"),
    path("user-stays/<slug>/", UserStayDetailView.as_view(), name="user-stay"),
    path("events/", EventListView.as_view(), name="events-list"),
    path("all-stays/", AllStaysListView.as_view(), name="all-stays-list"),
    path("create-stay/", StaysCreateView.as_view(), name="stays-create"),
    path("stays/<slug>/", StaysDetailView.as_view(), name="stays-detail"),
    path(
        "stays/<stay_slug>/add-view/",
        CreateStayViews.as_view(),
        name="add_view_to_stay",
    ),
    path(
        "stays/<stay_slug>/create-event/",
        EventCreateView.as_view(),
        name="create_event_to_stay",
    ),
    path(
        "stays/<stay_slug>/create-lodge-package/",
        LodgePackageBookingCreateView.as_view(),
        name="create_lodge_package_stay",
    ),
    path(
        "stays/<stay_slug>/create-lodge-package-installment/",
        LodgePackageBookingInstallmentCreateView.as_view(),
        name="create_lodge_package_stay_installment",
    ),
    path(
        "event/create-transport/",
        EventTransportCreateView.as_view(),
        name="create_event_transport",
    ),
    path(
        "stays/<stay_slug>/images/",
        StayImageListView.as_view(),
        name="stay-images-list",
    ),
    path(
        "stays/<stay_slug>/create-image/",
        StayImageCreateView.as_view(),
        name="stay-images-create",
    ),
    path(
        "stays/<stay_slug>/images/<int:pk>/",
        StayImageDetailView.as_view(),
        name="stay-images-detail",
    ),
    path("stays/<stay_slug>/reviews/", ReviewListView.as_view(), name="reviews-list"),
    path(
        "stays/<stay_slug>/reviews/<int:pk>/",
        ReviewDetailView.as_view(),
        name="reviews-detail",
    ),
    path(
        "stays/<stay_slug>/create-review/",
        ReviewCreateView.as_view(),
        name="reviews-create",
    ),
    path("stays/<stay_slug>/add-to-cart/", CartItemAPIView.as_view(), name="add-cart"),
    path(
        "user-cart/<int:pk>/",
        CartDetailView.as_view(),
        name="detail-cart-item",
    ),
    path("user-cart/", CartListView.as_view(), name="user-cart-items"),
    path("user-orders/", OrderListView.as_view(), name="orders-list"),
    path("user-orders/paid/", OrderPaidListView.as_view(), name="orders-paid-list"),
    path("user-orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "stays/<stay_slug>/add-to-order/",
        OrderCreateView.as_view(),
        name="order-create",
    ),
    path(
        "stays/<stay_slug>/save/",
        SaveStaysCreateView.as_view(),
        name="save-stay",
    ),
    path(
        "stays/<stay_id>/delete/",
        SaveStaysDeleteView.as_view(),
        name="delete-stay",
    ),
    path(
        "user-saved-stays/",
        SaveStaysListView.as_view(),
        name="user-saved-stays",
    ),
    path(
        "user-saved-stays/<int:pk>/",
        SaveStaysDetailView.as_view(),
        name="user-saved-stays-detail",
    ),
    path(
        "stays/<stay_slug>/add-room-type/",
        RoomTypeCreateView.as_view(),
        name="room-type-create",
    ),
    path(
        "stays/<stay_slug>/room-types/",
        RoomTypeListView.as_view(),
        name="room-type-list",
    ),
    path(
        "stays/<stay_slug>/room-types/<slug>/",
        RoomTypeDetailView.as_view(),
        name="room-type-detail",
    ),
    path(
        "stays/<stay_slug>/room-detail-types/",
        RoomTypeDetailListView.as_view(),
        name="room-detail-type-list",
    ),
    path(
        "stays/<stay_slug>/room-detail-types/<int:pk>/",
        RoomTypeListDetailView.as_view(),
        name="room-detail-type-detail",
    ),
    path(
        "room-types/<room_type_slug>/availabilities/",
        RoomAvailabilityListView.as_view(),
        name="room-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/resident-availabilities/",
        RoomAvailabilityResidentView.as_view(),
        name="room-resident-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/resident-availabilities/<slug>/",
        RoomAvailabilityResidentDeleteView.as_view(),
        name="room-resident-availability-delete",
    ),
    path(
        "room-types/<room_type_slug>/nonresident-availabilities/<slug>/",
        RoomAvailabilityNonResidentDeleteView.as_view(),
        name="room-non-resident-availability-delete",
    ),
    path(
        "room-types/<room_type_slug>/nonresident-availabilities/",
        RoomAvailabilityNonResidentView.as_view(),
        name="room-non-resident-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/availabilities/<slug>/",
        RoomAvailabilityDetailView.as_view(),
        name="room-availability-detail",
    ),
    path(
        "room-types/<slug>/delete-resident-availability/",
        RoomAvailabilityResidentDeleteView.as_view(),
        name="room-resident-availability-delete",
    ),
    path(
        "room-types/<slug>/delete-nonresident-availability/",
        RoomAvailabilityNonResidentDeleteView.as_view(),
        name="room-nonresident-availability-delete",
    ),
    path(
        "room-types/<room_type_slug>/add-availability/",
        RoomAvailabilityCreateView.as_view(),
        name="room-availability-create",
    ),
    path(
        "resident-guests/<int:pk>/",
        RoomAvailabilityResidentGuestDetailView.as_view(),
        name="resident-guest-detail",
    ),
    path(
        "nonresident-guests/<int:pk>/",
        RoomAvailabilityNonResidentGuestDetailView.as_view(),
        name="nonresident-guest-detail",
    ),
    path(
        "stays/<stay_slug>/resident-other-fees/",
        OtherFeesResidentListView.as_view(),
        name="resident-other-fees-list",
    ),
    path(
        "stays/<stay_slug>/nonresident-other-fees/",
        OtherFeesNonResidentListView.as_view(),
        name="nonresident-other-fees-list",
    ),
    path(
        "stays/<stay_slug>/resident-other-fees/<int:pk>/",
        OtherFeesResidentDetailView.as_view(),
        name="resident-other-fees-detail",
    ),
    path(
        "stays/<stay_slug>/nonresident-other-fees/<int:pk>/",
        OtherFeesNonResidentDetailView.as_view(),
        name="nonresident-other-fees-detail",
    ),
    path(
        "room-types/<room_type_slug>/add-booking/",
        BookingsCreateView.as_view(),
        name="room-booking-create",
    ),
    path(
        "user-stays-email/",
        UserStaysEmail.as_view(),
        name="user-stays-email",
    ),
    path(
        "user-stays-email/<slug>/agents/",
        UserStayEmailAgentListView.as_view(),
        name="user-stays-email-agents",
    ),
    path(
        "user-stays-email/<slug>/user-agents-email/",
        UserAgentAccessByEmailListView.as_view(),
        name="user-agents-email",
    ),
    path(
        "user-stays-email/<slug>/not-user-agents-email/",
        UserAgentAccessByEmailNotVerifiedListView.as_view(),
        name="not-user-agents-email",
    ),
    path(
        "user-stays-email/<slug>/verified-property-access/",
        PropertyAccessListView.as_view(),
        name="verified-property-access",
    ),
    path(
        "user-stays-email/<slug>/not-verified-property-access/",
        ProperyAccessNotVerifiedListView.as_view(),
        name="not-verified-property-access",
    ),
    path(
        "user-stays-email/<slug>/agents-not-verified/",
        UserStayEmailAgentNotVerifiedListView.as_view(),
        name="user-stays-not-verified-email-agents",
    ),
    path(
        "property-access/<int:pk>/",
        PropertyAccessDetailView.as_view(),
        name="property-access-detail",
    ),
    path(
        "agent-access/<int:pk>/",
        AgentAccessDetailView.as_view(),
        name="agent-access-detail",
    ),
    path(
        "user-stays-email/<slug>/",
        UserStaysEmailDetailView.as_view(),
        name="user-stays-detail-email",
    ),
    path(
        "test-partner-stays/",
        TestPartnerStaysListView.as_view(),
        name="test-partner-stays-list",
    ),
    path(
        "partner-stays/",
        PartnerStaysListView.as_view(),
        name="partner-stays-list",
    ),
    path(
        "all-partner-stays/",
        CombinedPartnerStaysListView.as_view(),
        name="all-partner-stays-list",
    ),
    path(
        "agent-access-by-email/<int:pk>/",
        AgentAccessByEmailDetailView.as_view(),
        name="agent-access-by-email-detail",
    ),
    path(
        "agent-access-by-email/check-invitation/",
        CheckAgentByEmailExistsView.as_view(),
        name="check-agent-by-email-exists",
    ),
    path(
        "property-access/check-invitation/",
        CheckPropertyAccessExistsView.as_view(),
        name="check-property-access-exists",
    ),
    path(
        "partner-stays/<list_ids>/",
        PartnerStaysDetailView.as_view(),
        name="partner-stays-detail",
    ),
    path(
        "partner-stays-without-access/",
        PartnerStaysWithoutContractView.as_view(),
        name="partner-stays-without-access",
    ),
    path(
        "partner-stays/<stay_slug>/activities/",
        ActivityFeesListCreateView.as_view(),
        name="activity-fees-list-create",
    ),
    path(
        "partner-stays/<stay_slug>/park-fees/",
        ParkFeesListCreateView.as_view(),
        name="park-fees-list-create",
    ),
    path(
        "partner-stays/<stay_slug>/park-fees/<int:pk>/",
        ParkFeesDetailView.as_view(),
        name="park-fees-detail",
    ),
    path(
        "partner-stays/<stay_slug>/activities/<int:pk>/",
        ActivityFeesDetailView.as_view(),
        name="activity-fees-detail",
    ),
    path("send-request-mail/", RequestMail.as_view(), name="send-request-mail"),
    path(
        "room-types/<room_type_slug>/bookings/",
        BookingsListView.as_view(),
        name="room-booking-list",
    ),
    path("schedule-demo/", ScheduleDemo.as_view(), name="schedule-demo"),
]
