from django.urls import path
from .views import *


urlpatterns = [
    path("stays/", StaysListView.as_view(), name="stays-list"),
    path(
        "highlighted-stays/",
        HighlightedStaysListView.as_view(),
        name="highlighted-stays-list",
    ),
    path(
        "highlighted-stays/<slug>/",
        HighlightedStaysDetailView.as_view(),
        name="highlighted-stays-detail",
    ),
    path("user-stays/", UserStays.as_view(), name="user-stays-list"),
    path("user-stays/<slug>/", UserStayDetailView.as_view(), name="user-stay"),
    path("events/", EventListView.as_view(), name="events-list"),
    path("all-stays/", AllStaysListView.as_view(), name="all-stays-list"),
    path("create-stay/", StaysCreateView.as_view(), name="stays-create"),
    path("stays/<slug>/", StaysDetailView.as_view(), name="stays-detail"),
    path(
        "stays/<stay_slug>/add-view/",
        CreateStayViews.as_view(),
        name="add_view_to_stay",
    ),
    path(
        "stays/<stay_slug>/create-event/",
        EventCreateView.as_view(),
        name="create_event_to_stay",
    ),
    path(
        "stays/<stay_slug>/create-lodge-package/",
        LodgePackageBookingCreateView.as_view(),
        name="create_lodge_package_stay",
    ),
    path(
        "stays/<stay_slug>/create-lodge-package-installment/",
        LodgePackageBookingInstallmentCreateView.as_view(),
        name="create_lodge_package_stay_installment",
    ),
    path(
        "event/create-transport/",
        EventTransportCreateView.as_view(),
        name="create_event_transport",
    ),
    path(
        "stays/<stay_slug>/images/",
        StayImageListView.as_view(),
        name="stay-images-list",
    ),
    path(
        "stays/<stay_slug>/create-image/",
        StayImageCreateView.as_view(),
        name="stay-images-create",
    ),
    path(
        "stays/<stay_slug>/images/<int:pk>/",
        StayImageDetailView.as_view(),
        name="stay-images-detail",
    ),
    path("stays/<stay_slug>/reviews/", ReviewListView.as_view(), name="reviews-list"),
    path(
        "stays/<stay_slug>/reviews/<int:pk>/",
        ReviewDetailView.as_view(),
        name="reviews-detail",
    ),
    path(
        "stays/<stay_slug>/create-review/",
        ReviewCreateView.as_view(),
        name="reviews-create",
    ),
    path("stays/<stay_slug>/add-to-cart/", CartItemAPIView.as_view(), name="add-cart"),
    path(
        "user-cart/<int:pk>/",
        CartDetailView.as_view(),
        name="detail-cart-item",
    ),
    path("user-cart/", CartListView.as_view(), name="user-cart-items"),
    path("user-orders/", OrderListView.as_view(), name="orders-list"),
    path("user-orders/paid/", OrderPaidListView.as_view(), name="orders-paid-list"),
    path("user-orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "stays/<stay_slug>/add-to-order/",
        OrderCreateView.as_view(),
        name="order-create",
    ),
    path(
        "stays/<stay_slug>/save/",
        SaveStaysCreateView.as_view(),
        name="save-stay",
    ),
    path(
        "stays/<stay_id>/delete/",
        SaveStaysDeleteView.as_view(),
        name="delete-stay",
    ),
    path(
        "user-saved-stays/",
        SaveStaysListView.as_view(),
        name="user-saved-stays",
    ),
    path(
        "user-saved-stays/<int:pk>/",
        SaveStaysDetailView.as_view(),
        name="user-saved-stays-detail",
    ),
    path(
        "stays/<stay_slug>/add-room-type/",
        RoomTypeCreateView.as_view(),
        name="room-type-create",
    ),
    path(
        "stays/<stay_slug>/room-types/",
        RoomTypeListView.as_view(),
        name="room-type-list",
    ),
    path(
        "stays/<stay_slug>/room-types/<slug>/",
        RoomTypeDetailView.as_view(),
        name="room-type-detail",
    ),
    path(
        "room-types/<room_type_slug>/availabilities/",
        RoomAvailabilityListView.as_view(),
        name="room-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/resident-availabilities/",
        RoomAvailabilityResidentView.as_view(),
        name="room-resident-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/resident-availabilities/<slug>/",
        RoomAvailabilityResidentDeleteView.as_view(),
        name="room-resident-availability-delete",
    ),
    path(
        "room-types/<room_type_slug>/nonresident-availabilities/<slug>/",
        RoomAvailabilityNonResidentDeleteView.as_view(),
        name="room-non-resident-availability-delete",
    ),
    path(
        "room-types/<room_type_slug>/nonresident-availabilities/",
        RoomAvailabilityNonResidentView.as_view(),
        name="room-non-resident-availability-list",
    ),
    path(
        "room-types/<room_type_slug>/availabilities/<slug>/",
        RoomAvailabilityDetailView.as_view(),
        name="room-availability-detail",
    ),
    path(
        "room-types/<room_type_slug>/add-availability/",
        RoomAvailabilityCreateView.as_view(),
        name="room-availability-create",
    ),
    path(
        "stays/<stay_slug>/resident-other-fees/",
        OtherFeesResidentListView.as_view(),
        name="resident-other-fees-list",
    ),
    path(
        "stays/<stay_slug>/nonresident-other-fees/",
        OtherFeesNonResidentListView.as_view(),
        name="nonresident-other-fees-list",
    ),
    path(
        "stays/<stay_slug>/resident-other-fees/<int:pk>/",
        OtherFeesResidentDetailView.as_view(),
        name="resident-other-fees-detail",
    ),
    path(
        "stays/<stay_slug>/nonresident-other-fees/<int:pk>/",
        OtherFeesNonResidentDetailView.as_view(),
        name="nonresident-other-fees-detail",
    ),
    path(
        "room-types/<room_type_slug>/add-booking/",
        BookingsCreateView.as_view(),
        name="room-booking-create",
    ),
    path(
        "user-stays-email/",
        UserStaysEmail.as_view(),
        name="user-stays-email",
    ),
    path(
        "user-stays-email/<slug>/",
        UserStaysEmailDetailView.as_view(),
        name="user-stays-detail-email",
    ),
    path(
        "partner-stays/",
        PartnerStaysListView.as_view(),
        name="partner-stays-list",
    ),
    path(
        "partner-stays/<int:pk>/",
        PartnerStaysDetailView.as_view(),
        name="partner-stays-detail",
    ),
    path(
        "partner-stays/<stay_slug>/activities/",
        ActivityFeesListCreateView.as_view(),
        name="activity-fees-list-create",
    ),
    path("send-request-mail/", RequestMail.as_view(), name="send-request-mail"),
    path(
        "room-types/<room_type_slug>/bookings/",
        BookingsListView.as_view(),
        name="room-booking-list",
    ),
]
