# Generated by Django 3.2 on 2022-05-21 10:19

import core.utils
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_car', models.CharField(blank=True, choices=[('LARGE 4x4', 'LARGE 4x4'), ('SMALL 4x4', 'SMALL 4x4'), ('VAN', 'VAN'), ('SEDAN', 'SEDAN'), ('SMALL CAR', 'SMALL CAR')], max_length=100)),
                ('price', models.FloatField(blank=True, help_text='Price per 10km', null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('has_air_condition', models.BooleanField(default=False)),
                ('fm_radio', models.BooleanField(default=False)),
                ('cd_player', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('audio_input', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('overhead_passenger_airbag', models.BooleanField(default=False)),
                ('side_airbag', models.BooleanField(default=False)),
                ('power_locks', models.BooleanField(default=False)),
                ('power_mirrors', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('safety_tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="Separate each tools by using ' , '. Eg Spare wheel, Carjack", null=True, size=None)),
                ('open_roof', models.BooleanField(default=False)),
                ('dropoff_city', models.CharField(blank=True, max_length=350, null=True)),
                ('dropoff_country', models.CharField(blank=True, max_length=350, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=core.utils.transportation_image_thumbnail)),
                ('main', models.BooleanField(default=False)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_images', to='transport.transportation')),
            ],
        ),
    ]
