# Generated by Django 3.2 on 2022-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='vehicle_color',
            field=models.CharField(blank=True, help_text='eg. Red or #FF0000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
