# Generated by Django 3.2 on 2022-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
