# Generated by Django 3.2 on 2022-05-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_cart_order_review_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='destination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='starting_point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
