# Generated by Django 3.2 on 2022-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20220605_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_per_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_per_day',
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
