# Generated by Django 3.2 on 2022-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20220606_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='children_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='covid_19_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='covid_19_compliance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='damage_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='refaundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='refund_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
