# Generated by Django 3.2 on 2022-06-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20220612_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='refaundable',
            new_name='refundable',
        ),
    ]
