# Generated by Django 3.2 on 2022-07-07 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_remove_transportation_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vehicle_plate',
        ),
        migrations.AddField(
            model_name='transportation',
            name='bags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='four_wheel_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='included_in_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, help_text="Separate each items by using ' , '. Eg Theft protection, Third party cover", null=True, size=None),
        ),
        migrations.AddField(
            model_name='transportation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='transmission',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type_of_car',
            field=models.CharField(blank=True, choices=[('LARGE 4x4', 'LARGE 4x4'), ('SMALL 4x4', 'SMALL 4x4'), ('VAN', 'VAN'), ('MEDIUM', 'MEDIUM'), ('MOTORBIKE', 'MOTORBIKE'), ('PICKUP TRUCK', 'PICKUP TRUCK'), ('SEDAN', 'SEDAN')], max_length=100),
        ),
    ]
