# Generated by Django 3.2 on 2022-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_auto_20220707_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='open_roof',
            field=models.BooleanField(default=False),
        ),
    ]
