# Generated by Django 3.2 on 2022-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_transportation_open_roof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportation',
            options={'verbose_name': 'Transportation', 'verbose_name_plural': 'Transportations'},
        ),
    ]
