# Generated by Django 3.2 on 2022-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
