# Generated by Django 3.2 on 2022-08-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_auto_20220823_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='reviewing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='user_has_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
