# Generated by Django 3.2 on 2022-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_auto_20220823_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_types',
            field=models.CharField(blank=True, choices=[('ONE WAY', 'ONE WAY'), ('RETURN', 'RETURN')], max_length=100, null=True),
        ),
    ]
