# Generated by Django 3.2 on 2022-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_flight_flight_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_admin_entry',
            field=models.BooleanField(default=False),
        ),
    ]
