# Generated by Django 3.2 on 2022-08-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0024_flight_is_admin_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('starting_point', models.CharField(blank=True, max_length=250, null=True)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_people', models.IntegerField(default=1)),
                ('transfer_types', models.CharField(blank=True, choices=[('ONE WAY', 'ONE WAY'), ('RETURN', 'RETURN')], max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_has_ordered', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('reviewing', models.BooleanField(default=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Transfer',
                'verbose_name_plural': 'General Transfers',
            },
        ),
    ]
