# Generated by Django 3.2 on 2022-06-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletrip',
            name='tags',
        ),
        migrations.AddField(
            model_name='singletrip',
            name='beach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='boat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='cabin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='camping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='caves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='couples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='creative_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='desert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='familiy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='hiking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='honeymoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='lake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='mountain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='surfing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='treehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='tropical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='activity_number_of_groups',
            field=models.IntegerField(default=0, help_text='Set the default number of group coming for this experience. Make sure the experience supports a pricing plan of per group.'),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='activity_number_of_sessions',
            field=models.IntegerField(default=0, help_text='Set the default number of sessions for this experience. Make sure the experience supports a pricing plan of per session.'),
        ),
    ]
