# Generated by Django 3.2 on 2022-06-15 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0004_rename_familiy_singletrip_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1, help_text='Format should be a number. It should be between 1 and 12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommended_trip.singletrip')),
            ],
        ),
    ]
