# Generated by Django 3.2 on 2022-06-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0005_recommendedmonths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmonths',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='recommended_trip.singletrip'),
        ),
    ]
