# Generated by Django 3.2 on 2022-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0006_alter_recommendedmonths_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='how_long_is_trip',
            field=models.IntegerField(default=3),
        ),
    ]
