# Generated by Django 3.2 on 2022-06-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0007_singletrip_how_long_is_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletrip',
            name='activity_non_resident',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='activity_number_of_groups',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='activity_number_of_people',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='activity_number_of_sessions',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='activity_pricing_type',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='how_long_is_trip',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='stay_non_resident',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='stay_num_of_adults',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='stay_num_of_children',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='stay_plan',
        ),
        migrations.RemoveField(
            model_name='singletrip',
            name='user_need_a_driver',
        ),
    ]
