# Generated by Django 3.2 on 2022-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0008_auto_20220615_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='price_budget',
            field=models.CharField(choices=[(1, 'Budget'), (2, 'MID RANGE'), (3, 'LUXURY')], default='1', max_length=100),
        ),
    ]
