# Generated by Django 3.2 on 2022-07-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0013_auto_20220717_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singletrip',
            old_name='princing_type',
            new_name='pricing_type',
        ),
    ]
