# Generated by Django 3.2 on 2022-07-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0014_rename_princing_type_singletrip_pricing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletrip',
            name='starting_point',
        ),
    ]
