# Generated by Django 3.2 on 2022-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0015_remove_singletrip_starting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='area_covered',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
