# Generated by Django 3.2 on 2022-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0017_alter_triphighlight_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singletrip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curated trip', 'verbose_name_plural': 'Curated trips'},
        ),
    ]
