# Generated by Django 3.2 on 2022-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0019_auto_20220811_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='total_number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
