# Generated by Django 3.2 on 2022-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0026_remove_singletrip_max_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singletrip',
            name='price_non_resident',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
