# Generated by Django 3.2 on 2022-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0029_auto_20220827_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletrip',
            name='families',
        ),
        migrations.AddField(
            model_name='singletrip',
            name='walking_hiking',
            field=models.BooleanField(default=False, verbose_name='Walking/hinking'),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='all_female',
            field=models.BooleanField(default=False, verbose_name='All-female'),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='cross_country',
            field=models.BooleanField(default=False, verbose_name='Cross-country'),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='family',
            field=models.BooleanField(default=False, verbose_name='Families'),
        ),
        migrations.AlterField(
            model_name='singletrip',
            name='park_conservancies',
            field=models.BooleanField(default=False, verbose_name='Park & Conservancies'),
        ),
    ]
