# Generated by Django 3.2 on 2022-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0031_requestcustomtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrip',
            name='old_price',
            field=models.FloatField(blank=True, help_text='add the previous price(old price)', null=True),
        ),
    ]
