# Generated by Django 3.2 on 2022-11-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_trip', '0035_singletrip_has_holiday_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='recommended_trip.singletrip')),
            ],
            options={
                'verbose_name': 'Available date',
                'verbose_name_plural': 'Available dates',
                'ordering': ['-created_at'],
            },
        ),
    ]
